"""Recompute the numbers quoted in paper/paper.tex from the frozen result files
and check that each formatted value appears in the manuscript.

    python -m scripts.check_numbers

Exit status 1 lists every value that is missing or differs. Numbers taken from
the literature are not checked here; they carry a citation in the text.
"""
import json
import re
import sys
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path

import pandas as pd
import torch

from src import quantize
from src.config import load_config
from src.nas.search import build_encoder

cfg = load_config()
RES = Path(cfg["paths"]["results_dir"])
ROOT = RES.parents[1]
TEX = " ".join((ROOT / "paper" / "paper.tex").read_text(encoding="utf-8").split())
missing: list[str] = []
notes: list[str] = []


def f(x: float, nd: int) -> str:
    """Round half up on the stored decimal value (0.3595 -> 0.360), the rule the
    tables use; Python's float formatting would print 0.359."""
    return str(Decimal(str(x)).quantize(Decimal(1).scaleb(-nd), rounding=ROUND_HALF_UP))


def expect(text: str, why: str) -> None:
    if text not in TEX:
        missing.append(f"{why}: '{text}' not in paper.tex")


def load(name: str):
    return json.loads((RES / name).read_text(encoding="utf-8"))


# Table 1 is the seeded rerun (scripts/run_matrix.py -> matrix_summary.json, written to
# paper/tab_matrix.tex by scripts/make_tab_matrix.py); the June run gives the architectures.
summary = load("results_summary.json")
june = {(r.arm, r.precision): r for r in pd.read_csv(RES / "results_matrix.csv").itertuples(index=False)}
cell = {(r["arm"], r["precision"]): r for r in load("matrix_summary.json")}

# ---- Table 1: every row, bold and dagger marks ignored
ARM = {"nas": "NAS", "micro_nas": "Micro-NAS", "binarized_micro_nas": r"Bin.\,$\mu$NAS"}
PREC = {"fp32": "FP32", "int8": "INT8", "binary": "Binary"}
TABM = " ".join((ROOT / "paper" / "tab_matrix.tex").read_text(encoding="utf-8").split())
if "Generated by scripts/make_tab_matrix.py" not in TABM:
    missing.append("paper/tab_matrix.tex was not written by scripts/make_tab_matrix.py")
if r"\input{tab_matrix}" not in TEX:
    missing.append("paper.tex does not include tab_matrix.tex")
plain = re.sub(r"\\textbf\{([^}]*)\}", r"\1", TABM).replace(r"$^\dagger$", "")
for (arm, prec), r in cell.items():
    energy = f(r["energy_uj"], 1) if r["energy_uj"] >= 100 else f(r["energy_uj"], 2)
    row = (f"{ARM[arm]} & {PREC[prec]} & {f(r['auc'], 3)}$\\pm${f(r['auc_sd'], 3)} & {f(r['mrr'], 3)} & "
           f"{f(r['ndcg@10'], 3)} & {f(r['size_kb'], 1)} & {energy}")
    if row not in plain:
        missing.append(f"Table 1 row {arm}/{prec}: expected '{row}'")
if {r["n"] for r in cell.values()} != {3}:
    missing.append("Table 1 is described as three seeds; matrix_summary has another count")

# ---- headline numbers
mi8, ni8 = cell[("micro_nas", "int8")], cell[("nas", "int8")]
nrms = load("p1_summary.json")["nrms/nrms_reduced"]["en_auc"]["mean"]
expect(f"scores {f(mi8['auc'], 3)} AUC at an estimated {f(mi8['size_kb'], 0)}\\,KB", "abstract, constrained INT8")
expect(f"{f(ni8['auc'], 3)} at {f(ni8['size_kb'], 0)}\\,KB", "abstract, unconstrained INT8")

# ---- search space, run time, costs
space = cfg["nas"]["search_space"]
n_arch = len(space["channels"]) * len(space["depth"]) * len(space["out_dim"])
expect(f"holds {n_arch} architectures", "search-space size")
expect(f"take {f(sum(r['minutes'] for r in cell.values()) / 60, 1)} hours of training for three seeds",
       "training time of the matrix")
archs = {a: summary["best_arch"][a] for a in ARM}
expect(", ".join(f"{a['channels']}-{a['depth']}-{a['out_dim']}" for a in list(archs.values())[:2])
       + f" and {archs['binarized_micro_nas']['channels']}-{archs['binarized_micro_nas']['depth']}-"
         f"{archs['binarized_micro_nas']['out_dim']}", "searched architectures")
macs = [cell[(a, "fp32")]["macs"] / 1e6 for a in ARM]
expect(f"{f(macs[0], 1)}, {f(macs[1], 2)} and {f(macs[2], 2)} million", "MACs per title")
expect(f"({f(macs[1], 2)}\\,M and {f(macs[2], 2)}\\,M)", "constrained winners over the 2 M bound")
if not all(m > 2.0 for m in macs[1:]):
    missing.append("text says both constrained winners exceed 2 M MACs; they do not")
shares = []
for a in ARM:
    enc = quantize.convert_to_quant(build_encoder(cfg, archs[a]), "int8")
    shares.append(round(100 * (1 - quantize.quant_fp_fraction(enc))))
expect(f"cover {shares[0]}\\%, {shares[1]}\\% and {shares[2]}\\%", "quantised share of parameters")
e_ratio = [cell[(a, "fp32")]["energy_uj"] / cell[(a, "int8")]["energy_uj"] for a in ARM]
s_ratio = [cell[(a, "fp32")]["size_kb"] / cell[(a, "int8")]["size_kb"] for a in ARM]
expect(f"falls {f(min(e_ratio), 1)} to {f(max(e_ratio), 1)} times", "FP32/INT8 energy ratio")
expect(f"size 1.2 to\n{f(max(s_ratio), 0)} times".replace("\n", " ").replace("1.2", f(min(s_ratio), 1)),
       "FP32/INT8 size ratio")
d_auc = max(abs(cell[(a, "int8")]["auc"] - cell[(a, "fp32")]["auc"]) for a in ARM)
expect(f"changes AUC by at most {f(d_auc, 3)}", "FP32 to INT8 AUC change")
drop = [cell[(a, "fp32")]["auc"] - cell[(a, "binary")]["auc"] for a in ARM]
expect(f"it loses {f(min(drop), 3)} to {f(max(drop), 3)} AUC", "one-bit loss against FP32")
expect(f"is {f(mi8['ram_kb'], 0)}\\,KB for the constrained model and {f(ni8['ram_kb'], 0)}\\,KB", "RAM estimate")
expect(f"{f(mi8['auc'], 3)}, {f(mi8['size_kb'], 0)}\\,KB, {f(mi8['energy_uj'], 1)}\\uJ", "Fig. 2 sentence")
expect(f"({f(ni8['auc'], 3)}, {f(ni8['size_kb'], 0)}\\,KB)", "Fig. 2 sentence, unconstrained")
if not mi8["auc"] >= nrms:
    missing.append("'lowest cost at the accuracy of the reduced NRMS': eight-bit Micro-NAS is below it")
max_sd = max(r["auc_sd"] for r in cell.values())
expect(f"seeds reach {f(max_sd, 3)}, so smaller gaps", "abstract, seed spread")
expect(f"standard deviation over seeds reaches {f(max_sd, 3)}", "seed spread in Table 1")
diff = {k: abs(june[k].auc - cell[k]["auc"]) for k in cell}
worst = max(diff, key=diff.get)
expect(f"lies within {f(diff[worst], 3)} of the new mean", "June single runs against the rerun")
expect(f"one-bit constrained model ({f(june[worst].auc, 3)} in June)", "largest June difference")
if worst != ("micro_nas", "binary"):
    missing.append(f"the largest June difference is {worst}, not the one-bit constrained model")

# ---- laptop latency
lat = load("latency.json")
cpu = [r["cpu_onnx_ms"] for r in lat]
expect(f"{f(min(cpu), 2)}--{f(max(cpu), 2)}\\,ms on CPU", "CPU latency range")
if max(r["gpu_ms"] for r in lat) >= 0.7:
    missing.append("'under 0.7 ms on GPU' does not hold")

# ---- heuristics (P1)
heur = load("p1_heuristics.json")["heuristics"]["results"]
expect(f"popularity gives {f(heur['popularity']['all']['auc'], 3)}", "popularity AUC")
expect(f"category labels {f(heur['category']['all']['auc'], 3)}", "category histogram AUC")
expect(f"network {f(heur['category']['all']['auc'], 3)}", "abstract, category histogram")
expect(f"or {f(heur['subcategory']['all']['auc'], 3)} with the finer", "subcategory histogram AUC")
cold = heur["category"]["0"]["n_impressions"] / heur["category"]["all"]["n_impressions"]
expect(f"For the {f(100 * cold, 0)}\\% of impressions", "share of impressions without history")
expect(f"popularity gives {f(heur['popularity']['0']['auc'], 3)} there", "popularity, no history")
expect(f"category distribution {f(heur['category']['0']['auc'], 3)}", "category prior, no history")

# ---- binary
imp = load("binary_improved.json")
naive = cell[("micro_nas", "binary")]
loss1 = cell[("micro_nas", "fp32")]["auc"] - naive["auc"]
expect(f"costs the constrained model {f(loss1, 3)} AUC ({f(naive['auc'], 3)} over three seeds)", "naive binary")
expect(f"cost the constrained model {f(loss1, 3)} AUC ({f(naive['auc'], 3)})", "abstract, naive binary")
rn = load("binary_reactnet.json")["summary"]                      # three seeds, scripts/run_binary.py
P1 = load("p1_summary.json")
expect(f"gives ${f(rn['auc'], 3)}\\pm{f(rn['auc_sd'], 3)}$ over the same seeds ({f(imp['result']['auc'], 3)} in "
       f"the single June run) at an estimated {f(rn['cost']['size_kb'], 0)}\\,KB: {f(rn['auc'] - naive['auc'], 3)} "
       f"above naive binarisation, {f(P1['nrms/nrms_reduced']['en_auc']['mean'] - rn['auc'], 3)} below the reduced "
       f"NRMS and {f(P1['student/distill_ft_en']['en_auc']['mean'] - rn['auc'], 3)} below the distilled encoder",
       "ReActNet, three seeds")
expect(f"reach {f(rn['auc'], 3)} at {f(rn['cost']['size_kb'], 0)}\\,KB", "abstract, ReActNet")
expect(f"reaches {f(rn['auc'], 3)} at {f(rn['cost']['size_kb'], 0)}\\,KB", "conclusion, ReActNet")
if sorted(rn["seeds"]) != sorted(r["seeds"] for r in cell.values())[0]:
    missing.append("ReActNet seeds differ from the matrix seeds ('over the same seeds')")

# ---- P1 aggregates (three seeds)
P = load("p1_summary.json")


def m(key, field="en_auc"):
    return P[key][field]["mean"]


ng, nr = m("nrms/nrms_glove"), m("nrms/nrms_reduced")
sc, ft, mx = m("student/scratch_en"), m("student/distill_ft_en"), m("student/distill_ft_mixed")
fz, tf, tl = m("student/distill_frozen"), m("teacher/teacher_frozen"), m("teacher/teacher_linear")
x = {k: m(k, "xlang_auc") for k in ("student/scratch_en", "student/distill_ft_en", "student/distill_ft_mixed",
                                   "student/distill_frozen", "teacher/teacher_frozen", "teacher/teacher_linear")}
expect(f"GloVe vectors scores {f(ng, 3)} over three seeds", "abstract, GloVe NRMS")
expect(f"random 256-dimensional table {f(nr, 3)}", "abstract, reduced NRMS")
expect(f"adds {f(ft - sc, 3)} AUC ({f(ft, 3)} against {f(sc, 3)})", "abstract, distillation gain")
expect(f"from {f(x['student/distill_ft_en'], 3)} to {f(x['student/distill_ft_mixed'], 3)} at a cost of "
       f"{f(ft - mx, 3)} in English", "abstract, mixed-language training")
expect(f"averages {f(nr, 3)} over\nthree seeds with a spread of {f(P['nrms/nrms_reduced']['en_auc']['std'], 3)}"
       .replace("\n", " "), "reduced NRMS mean and spread")
expect(f"NRMS reaches {f(ng, 3)}", "GloVe NRMS mean")
expect(f"scores {f(sc, 3)} from a random start and {f(ft, 3)} from the distilled", "scratch vs distilled")
expect(f"distillation is worth {f(ft - sc, 3)} here", "distillation gain")
abl = load("ablation.json")
expect(f"less than the {f(abl['distilled_init']['auc'] - abl['scratch']['auc'], 3)} of the June", "June ablation gain")
ratio = P["nrms/nrms_glove"]["settings"]["params"] / P["student/scratch_en"]["encoder_cost"]["params"]
expect(f"gap to GloVe NRMS is {f(ng - ft, 3)} with {ratio:.0f} times fewer parameters", "gap and parameter ratio")
expect(f"distilled encoder is {f(ft - heur['subcategory']['all']['auc'], 3)} above the subcategory", "vs subcategory")
expect(f"dev sets at {f(x['student/scratch_en'], 3)} on average", "scratch cross-lingual")
expect(f"scores {f(x['student/distill_frozen'], 3)} across languages against {f(fz, 3)} in English", "frozen student")
expect(f"(the teacher itself: {f(x['teacher/teacher_frozen'], 3)} against {f(tf, 3)})", "frozen teacher")
expect(f"raises English to {f(ft, 3)} but leaves the translations at {f(x['student/distill_ft_en'], 3)}", "ft_en")
pl = P["student/distill_ft_mixed"]["per_language"]
lo, hi = min(pl, key=lambda k: pl[k]["mean"]), max(pl, key=lambda k: pl[k]["mean"])
names = {"kat": "Georgian", "fin": "Finnish"}
expect(f"keeps {f(x['student/distill_ft_mixed'], 3)} across languages, from {f(pl[lo]['mean'], 3)} "
       f"({names.get(lo, lo)}) to {f(pl[hi]['mean'], 3)} ({names.get(hi, hi)}), for {f(mx, 3)} in English",
       "mixed-language per-language range")
expect(f"reaches {f(x['teacher/teacher_linear'], 3)} across languages", "teacher linear cross-lingual")
expect(f"comes within {f(abs(x['teacher/teacher_linear'] - x['student/distill_ft_mixed']), 3)} of that figure",
       "byte-CNN vs teacher-linear cross-lingual")
b = P["student/distill_ft_en"]["buckets"]
g = P["nrms/nrms_glove"]["buckets"]
expect(f"scores {f(b['1-5']['mean'], 3)} for readers with one to five clicks, {f(b['6-20']['mean'], 3)} for six to "
       f"twenty and {f(b['>20']['mean'], 3)} beyond, against {f(g['1-5']['mean'], 3)}, {f(g['6-20']['mean'], 3)} and "
       f"{f(g['>20']['mean'], 3)} for GloVe NRMS", "history buckets")
expect(f"translations stay {f(mx - x['student/distill_ft_mixed'], 3)} below English and "
       f"{f(ft - x['student/distill_ft_mixed'], 3)} below the English-only encoder", "limitations gaps")
expect(f"fourteen languages at {f(x['student/distill_ft_mixed'], 3)} AUC on average", "conclusion cross-lingual")
if len(P["student/distill_ft_en"]["seeds"]) != 3:
    missing.append("the text says three seeds; p1_summary has a different count")
TAB = (ROOT / "paper" / "tab_p1.tex").read_text(encoding="utf-8")
if "Generated by scripts/make_tables.py" not in TAB:
    missing.append("paper/tab_p1.tex was not written by scripts/make_tables.py")

# ---- reduced NRMS size: checked once the P1 record exists
p1_nrms = RES / "p1_nrms.json"
reduced = [v for k, v in (load("p1_nrms.json") if p1_nrms.exists() else {}).items()
           if k.startswith("nrms_reduced/")]
if reduced:
    st = reduced[0]["settings"]
    expect(f"{f(100 * st['embedding_params'] / st['params'], 0)}\\% of its {f(st['params'] / 1e6, 2)} million",
           "reduced NRMS parameters")
    expect(f"the table, {f(st['size_mb_fp32'], 0)}\\,MB)", "reduced NRMS size")
else:
    notes.append("reduced-NRMS parameter count (92%, 7.08 M, 27 MB) has no result file yet; "
                 "it is checked once p1_nrms.json holds an nrms_reduced run")

# deployed integer file and board measurements (scripts/deploy_boards.py, scripts/stedgeai_cloud.py)
dep_file, runs_file = RES / "deploy_int8.json", RES / "stedgeai_cloud" / "runs.jsonl"
if dep_file.exists() and runs_file.exists():
    dep = load("deploy_int8.json")
    bench = {}
    for line in runs_file.read_text(encoding="utf-8").splitlines():
        r = json.loads(line)
        if r.get("cmd") == "benchmark" and "_body_" in r.get("model", "") and (r.get("duration_ms") or -1) > 0:
            bench[(r["model"], r["board"])] = r
    h8 = bench[("micro_nas_64-5-384_body_int8qdq.onnx", "STM32H7B3I-DK")]
    h32 = bench[("micro_nas_64-5-384_body_fp32.onnx", "STM32H7B3I-DK")]
    f8 = bench[("micro_nas_64-5-384_body_int8qdq.onnx", "NUCLEO-F401RE")]
    f32 = bench[("micro_nas_64-5-384_body_fp32.onnx", "NUCLEO-F401RE")]
    expect(f"scores {f(dep['onnx_int8qdq']['auc'], 3)} ({f(dep['onnx_fp32']['auc'], 3)} at full precision)", "abstract, integer file")
    expect(f"scores {f(dep['onnx_int8qdq']['auc'], 3)} AUC against {f(dep['onnx_fp32']['auc'], 3)}", "results, integer file")
    expect(f"runs in {f(h8['duration_ms'], 1)}\\,ms per title on an STM32H7B3I-DK", "H7 latency")
    expect(f"and {f(f8['duration_ms'], 0)}\\,ms on a NUCLEO-F401RE", "F401 latency")
    expect(f"{f(h32['duration_ms'] / h8['duration_ms'], 1)} times faster than at full precision ({f(h32['duration_ms'], 1)}\\,ms)", "H7 speed-up")
    expect(f"with {f(h8['weights_bytes'] / 1024, 1)}\\,KB of weights, {f(h8['rom_bytes'] / 1024, 1)}\\,KB of flash", "H7 flash")
    expect(f"and {f(h8['ram_bytes'] / 1024, 1)}\\,KB of RAM, plus the {f(dep['byte_table_bytes'] / 1024, 1)}\\,KB byte table", "H7 RAM, table")
    expect(f"takes {f(f8['duration_ms'], 0)}\\,ms, no faster than full precision there ({f(f32['duration_ms'], 0)}\\,ms)", "F401 comparison")
else:
    notes.append("board results not present; deploy and board sentences unchecked")

# µNAS encoders under the board budgets (unas/, scripts/run_unas_full.py, scripts/export_int8.py, Table 3)
if (RES / "unas_summary.json").exists() and (RES / "int8_export.json").exists():
    U = {r["name"]: r for r in load("unas_summary.json")}
    q = load("int8_export.json")
    qs = q["summary"]
    h7, hh, f4, hf, h5 = (U[n] for n in ("mind_h7", "hand_64-2-384", "mind_f401", "hand_32-5-384", "hand_64-5-384"))
    m = lambda r, k: f(r[k]["mean"], 3)                                          # noqa: E731
    ref = qs["ref_64-5-384"]
    expect(f"(0.624 against 0.629 over three seeds)".replace("0.624", f(ref["onnx_int8qdq_auc"], 3))
           .replace("0.629", f(ref["torch_fp32_auc"], 3)), "reference 8-bit file, three seeds")
    expect(f"8-bit file costs {f(-ref['int8qdq_minus_fp32_auc'], 3)} AUC on average over three seeds",
           "reference 8-bit loss (mean of the per-seed differences)")
    final = {r["group"]: r for r in load("unas_summary.json") if "final choice" in r["label"]}
    h7n, f4n = final["h7"], final["f401"]
    ms = lambda r, b: r["boards"][b]["duration_ms"]                              # noqa: E731
    H7, F4 = "STM32H7B3I-DK", "NUCLEO-F401RE"
    in_budget = [r for r in load("unas_summary.json") if r["group"] != "none"]
    qkey = lambda r: ("unas_" + r["name"][len("mind_"):]) if r["name"].startswith("mind_") else r["name"]  # noqa: E731
    worst = max(abs(qs[qkey(r)]["onnx_int8qdq_auc"] - qs[qkey(r)]["torch_fp32_auc"]) for r in in_budget)
    expect(f"at most {f(worst, 3)}", "in-budget 8-bit loss")
    # abstract
    expect(f"finds encoders of {m(h7n, 'en_auc')} and {m(f4n, 'en_auc')} AUC against {m(hh, 'en_auc')} and "
           f"{m(hf, 'en_auc')} for the best hand-designed shapes", "abstract, final choices")
    expect(f"takes {f(ms(f4n, F4), 1)}\\,ms per title there, against {f(ms(hf, F4), 1)}\\,ms", "abstract, F401 board")
    # Table 3 paragraph
    expect(f"at {f(h7['macs'] / 1e6, 2)}\\,M multiply-accumulates and, within the F401 budget", "H7 MACs")
    expect(f"convolution at {f(f4['macs'] / 1e6, 2)}\\,M", "F401 MACs")
    expect(f"({f(h7['search_cos']['mean'], 3)} against {f(hh['search_cos']['mean'], 3)} and "
           f"{f(f4['search_cos']['mean'], 3)} against {f(hf['search_cos']['mean'], 3)})", "search cosines")
    expect(f"{m(h7, 'en_auc')} against {m(hh, 'en_auc')} AUC within the H7 budget and {m(f4, 'en_auc')} against "
           f"{m(hf, 'en_auc')} within the F401 budget", "recipe choices, AUC")
    expect(f"({m(h7, 'xlang_auc')} against {m(hh, 'xlang_auc')} and {m(f4, 'xlang_auc')} against "
           f"{m(hf, 'xlang_auc')} across the fourteen", "recipe choices, translations")
    rc = load("unas/rechoice.json")["searches"]
    words = {1: "first", 2: "second", 3: "third", 4: "fourth", 5: "fifth", 6: "sixth", 7: "seventh", 8: "eighth"}
    place = {s: 1 + [r["index"] for r in rc[s]["stage1"]].index(rc[s]["first_choice"]) for s in rc}
    expect(f"fall to {words[place['mind_h7']]} and {words[place['mind_f401']]} place", "recipe choices after full distillation")
    hist_f = {c["index"]: c for c in load("unas/mind_f401_history.json")["candidates"]}
    n_branch = sum(1 for b in hist_f[rc["mind_f401"]["best"]]["arch"]["conv_blocks"] if b["is_branch"])
    if n_branch != 1:
        missing.append(f"text says one residual branch; the final F401 choice has {n_branch}")
    expect(f"candidate {rc['mind_h7']['best']} (H7, {f(h7n['macs'] / 1e6, 2)}\\,M) and candidate "
           f"{rc['mind_f401']['best']} (F401, {f(f4n['macs'] / 1e6, 2)}\\,M", "final choices")
    d7 = h7n["en_auc"]["mean"] - hh["en_auc"]["mean"]
    d4 = f4n["en_auc"]["mean"] - hf["en_auc"]["mean"]
    expect(f"These reach {m(h7n, 'en_auc')} and {m(f4n, 'en_auc')} AUC, ahead of the hand-designed shapes by "
           f"{f(d7, 3)}, inside the spread over seeds, and by {f(d4, 3)}", "final choices against hand-designed")
    if not abs(d7) < max(h7n["en_auc"]["std"], hh["en_auc"]["std"]):
        missing.append("H7 final choice: the gap to 64-2-384 is not inside the spread over seeds")
    uf = load("unas_full.json")

    def mixed(name, field):
        runs = [v["results"] for k, v in uf.items() if k.startswith(f"{name}/distill_ft_mixed/")]
        if len(runs) != 3:
            missing.append(f"{name}: {len(runs)} mixed-language runs, the text assumes three")
        vals = [r["en"]["all"]["auc"] if field == "en" else r["mean_xlang_auc"] for r in runs]
        return f(sum(vals) / len(vals), 3)

    expect(f"read the translations at {mixed('mind_h7', 'x')} and {mixed('mind_f401', 'x')} and English at "
           f"{mixed('mind_h7', 'en')} and {mixed('mind_f401', 'en')}", "µNAS encoders, mixed-language clicks")
    p1s = load("p1_summary.json")
    expect(f"scores {m(h5, 'en_auc')} in this form and {f(p1s['student/distill_ft_en']['en_auc']['mean'], 3)} in its",
           "64-5-384 in both forms")
    expect(f"the H7 recipe choice was {f(h5['search_cos']['mean'] - h7['search_cos']['mean'], 3)} below",
           "search-recipe gap")
    expect(f"after full distillation {f(h5['teacher_cos_dev']['mean'] - h7['teacher_cos_dev']['mean'], 3)}",
           "full-distillation gap")
    # boards paragraph
    rows_b = [r for r in load("unas_summary.json") if r["boards"]]
    if min(rows_b, key=lambda r: ms(r, F4))["name"] != f4["name"] or len(rows_b) != 7:
        missing.append("'the recipe's F401 choice is the fastest of the seven encoders' on the F401 does not hold")
    if min(rows_b, key=lambda r: ms(r, H7))["name"] != f4n["name"]:
        missing.append("'the final F401 choice is the fastest on the STM32H7B3I-DK' does not hold")
    expect(f"encoders: {f(ms(f4, F4), 1)}\\,ms per title, against {f(ms(hf, F4), 1)}\\,ms for 32-5-384 and "
           f"{f(ms(h5, F4), 0)}\\,ms for 64-5-384", "F401 board, recipe choice and hand-designed")
    expect(f"{f(ms(hf, F4) / ms(f4, F4), 1)}\ntimes faster".replace("\n", " "), "F401 speed-up")
    expect(f"takes {f(ms(f4n, F4), 1)}\\,ms there, {f(ms(hf, F4) / ms(f4n, F4), 1)} times less than 32-5-384, and is "
           f"the fastest on the STM32H7B3I-DK ({f(ms(f4n, H7), 1)}\\,ms)", "final F401 choice on the boards")
    expect(f"64-2-384 is faster on that board ({f(ms(hh, H7), 1)}\\,ms) than both searched choices "
           f"({f(ms(h7, H7), 1)} and {f(ms(h7n, H7), 1)}\\,ms)", "H7 board")
    # conclusion
    expect(f"an encoder of {f(f4n['macs'] / 1e6, 2)}\\,M multiply-accumulates reaches {m(f4n, 'en_auc')} at "
           f"{f(ms(f4n, F4), 1)}\\,ms per title on that board, {f(d4, 3)} above the best hand-designed shape",
           "conclusion F401")
    # phone (FeedWell-Edge research screen, paper/results/phone/edge_bench)
    bench = RES / "phone" / "edge_bench"
    lat = {(r["kind"], r["threads"]): r for r in
           json.loads(sorted(bench.glob("latency_*.json"))[-1].read_text(encoding="utf-8"))["rows"]}
    chk = json.loads(sorted(bench.glob("check_*.json"))[-1].read_text(encoding="utf-8"))
    app = load("app_encoder.json")
    expect(f"the 8-bit encoder takes {f(lat[('int8', 1)]['medianMs'], 2)}\\,ms per title.", "abstract, phone")
    expect(f"(largest difference ${chk['int8']['maxAbsDiff']:.1e}".replace("e-07", "\\times10^{-7}"), "phone check")
    expect(f"takes {f(lat[('int8', 1)]['medianMs'], 2)}\\,ms per title on one core (median over "
           f"{lat[('int8', 1)]['repeats']:,} calls", "phone, 8-bit, one thread")
    expect(f"{f(lat[('int8', 2)]['medianMs'], 2)}\\,ms with two threads); the full-precision file takes "
           f"{f(lat[('fp32', 1)]['medianMs'], 2)}\\,ms", "phone, two threads and FP32")
    expect(f"The file scores {f(app['int8_file_auc']['en'], 3)} AUC in English and "
           f"{f(app['int8_file_mean_xlang_auc'], 3)} over the fourteen translations", "app encoder file")
    cyc = {}
    for line in (RES / "stedgeai_cloud" / "runs.jsonl").read_text(encoding="utf-8").splitlines():
        r = json.loads(line)
        if r.get("cmd") == "benchmark" and (r.get("duration_ms") or -1) > 0:
            cyc[(r["model"], r["board"])] = r
    c_f4 = cyc[("unas_f401_seed42_body_int8qdq.onnx", F4)]["cycles_by_macc"]
    c_hf = cyc[("hand_32-5-384_seed42_body_int8qdq.onnx", F4)]["cycles_by_macc"]
    expect(f"at {f(c_f4, 1)} cycles\nper multiply-accumulate against {f(c_hf, 1)}".replace("\n", " "), "cycles per MAC")
    rep = json.loads((RES / "stedgeai_cloud" / "hand_32-5-384_seed42_body_int8qdq__NUCLEO-F401RE.json")
                     .read_text(encoding="utf-8"))["info"]["graphs"][0]["nodes"]
    dw = {round(n["exec_time"]["cycles_by_macc"]) for n in rep
          if n.get("attributes", {}).get("is_depthwise") == "True" and n.get("exec_time")}
    first = next(n for n in rep if n["name"] == "_layers_0_conv_Conv_output_0")["exec_time"]["cycles_by_macc"]
    expect(f"depthwise layers take {dw.pop() if len(dw) == 1 else dw}", "depthwise cycles per MAC")
    expect(f"65 input\nchannels, {f(first, 1)}".replace("\n", " "), "first pointwise cycles per MAC")
    full = json.loads((RES / "stedgeai_cloud" / "unas_h7_seed42_body_int8full__STM32H7B3I-DK.json")
                      .read_text(encoding="utf-8"))["info"]["graphs"][0]["nodes"]
    fused = max(n["exec_time"]["duration_ms"] for n in full if n.get("exec_time"))
    expect(f"took {f(fused, 1)}\\,ms alone", "fused conv+pool kernel")
    port = load("unas/port_check.json")
    expect(f"{max(r['output_max_abs_diff'] for r in port.values()):.1e}".replace("e-05", r"\times10^{-5}"), "port check")
else:
    notes.append("µNAS results not present; Table 3 sentences unchecked")

for line in notes:
    print("note:", line)
if missing:
    print(f"{len(missing)} mismatch(es):")
    for line in missing:
        print("  -", line)
    sys.exit(1)
print("paper.tex agrees with paper/results")
