"""Write the LaTeX table of the P1 design experiments (paper/tab_p1.tex) from
paper/results/p1_summary.json and p1_heuristics.json, so no number is typed by
hand. Means and population standard deviations over the seeds.

    python -m scripts.make_tables
"""
import json
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path

from src.config import load_config

cfg = load_config()
RES = Path(cfg["paths"]["results_dir"])
S = json.loads((RES / "p1_summary.json").read_text(encoding="utf-8"))
H = json.loads((RES / "p1_heuristics.json").read_text(encoding="utf-8"))["heuristics"]["results"]
EOL = r" \\"
MIDRULE = r"\midrule"


def f(x, nd=3):
    return str(Decimal(str(x)).quantize(Decimal(1).scaleb(-nd), rounding=ROUND_HALF_UP))


def pm(st, nd=3):
    if not st:
        return "--"
    if st.get("std") is None:
        return f(st["mean"], nd)
    return f(st["mean"], nd) + r"$\pm$" + f(st["std"], nd)


def params(n):
    return (f"{n / 1e6:.2f}" + r"\,M") if n >= 1e6 else (f"{n / 1e3:.0f}" + r"\,k")


rows = []
for name, key in (("Popularity", "popularity"), ("Category histogram", "category"),
                  ("Subcategory histogram", "subcategory")):
    r = H[key]["all"]
    rows.append(f"{name} & -- & {f(r['auc'])} & {f(r['mrr'])} & {f(r['ndcg@10'])} & --" + EOL)
rows.append(MIDRULE)
nr, ng = S["nrms/nrms_reduced"], S["nrms/nrms_glove"]
rows.append(f"NRMS, reduced (random 256-d table) & {params(nr['settings']['params'])} & "
            f"{pm(nr['en_auc'])} & {pm(nr['en_mrr'])} & {pm(nr['en_ndcg10'])} & --" + EOL)
rows.append(f"NRMS, GloVe reference config. & {params(ng['settings']['params'])} & "
            f"{pm(ng['en_auc'])} & {pm(ng['en_mrr'])} & {pm(ng['en_ndcg10'])} & --" + EOL)
rows.append(MIDRULE)
tf, tl = S["teacher/teacher_frozen"], S["teacher/teacher_linear"]
rows.append(f"Frozen teacher + user encoder & -- & {pm(tf['en_auc'])} & {pm(tf['en_mrr'])} & "
            f"{pm(tf['en_ndcg10'])} & {pm(tf['xlang_auc'])}" + EOL)
rows.append(r"\quad + trainable linear map & -- & " + f"{pm(tl['en_auc'])} & {pm(tl['en_mrr'])} & "
            f"{pm(tl['en_ndcg10'])} & {pm(tl['xlang_auc'])}" + EOL)
rows.append(MIDRULE)
enc = params(S["student/scratch_en"]["encoder_cost"]["params"])
for name, key in (("Byte-CNN, random start, EN clicks", "student/scratch_en"),
                  ("Byte-CNN, random start, mixed clicks", "student/scratch_mixed"),
                  ("Byte-CNN, distilled, frozen", "student/distill_frozen"),
                  ("Byte-CNN, distilled start, EN clicks", "student/distill_ft_en"),
                  ("Byte-CNN, distilled start, mixed clicks", "student/distill_ft_mixed")):
    r = S[key]
    rows.append(f"{name} & {enc} & {pm(r['en_auc'])} & {pm(r['en_mrr'])} & {pm(r['en_ndcg10'])} & "
                f"{pm(r['xlang_auc'])}" + EOL)

seeds = S["student/distill_ft_en"]["seeds"]
head = r"""% Generated by scripts/make_tables.py from paper/results/p1_summary.json; do not edit.
\begin{table}[t]
\caption{Reference points and the reference byte-CNN (64-5-384, full precision) on MINDsmall
dev. Mean $\pm$ standard deviation over NSEEDS seeds; the last column is the mean AUC over the
fourteen xMIND translations; ``mixed clicks'' = each training instance shown in a random
xMIND language. Histogram scorers use MIND's editorial labels. Params\,=\,news encoder.}
\label{tab:p1}\centering\scriptsize\setlength{\tabcolsep}{3pt}
\resizebox{\linewidth}{!}{\begin{tabular}{lrcccc}
\toprule
Scorer & Params & AUC & MRR & nDCG@10 & 14-lang.\ AUC\\
\midrule
""".replace("NSEEDS", str(len(seeds)))
tail = r"""
\bottomrule
\end{tabular}}
\end{table}
"""
tex = head + "\n".join(rows) + tail
(Path("paper") / "tab_p1.tex").write_text(tex, encoding="utf-8")
print(tex)
